# Создание виртуального окружения и установка зависимостей
setup:
	python -m venv venv
	. venv/bin/activate && pip install -r requirements.txt

# Запуск сервера
run_server:
	. venv/bin/activate && python server.py

# Запуск клиента
run_client:
	. venv/bin/activate && python client.py
